FROM ubuntu:24.04
RUN apt-get update && apt-get install -y --no-install-recommends \
  libssl-dev ca-certificates \
  && apt-get clean && rm -rf /var/lib/apt/lists/*
COPY ./bin/lighthouse /usr/local/bin/lighthouse
