FROM ubuntu:24.04
RUN apt-get update && apt-get install -y --no-install-recommends \
  libssl-dev ca-certificates \
  && apt-get clean && rm -rf /var/lib/apt/lists/*
COPY ./bin/vibehouse /usr/local/bin/vibehouse
# ethereum-package invokes the binary as "lighthouse" when cl_type: lighthouse
RUN ln -s /usr/local/bin/vibehouse /usr/local/bin/lighthouse
