use super::{AttestationBase, AttestationElectra, AttestationRef};
use super::{
    ChainSpec, Domain, EthSpec, Fork, ForkName, Hash256, PublicKey, SecretKey, SelectionProof,
    Signature, SignedRoot,
};
use crate::Attestation;
use crate::context_deserialize;
use crate::test_utils::TestRandom;
use serde::{Deserialize, Serialize};
use ssz_derive::{Decode, Encode};
use superstruct::superstruct;
use test_random_derive::TestRandom;
use tree_hash_derive::TreeHash;

#[superstruct(
    variants(Base, Electra),
    variant_attributes(
        derive(
            Debug,
            Clone,
            PartialEq,
            Serialize,
            Deserialize,
            Encode,
            Decode,
            TestRandom,
            TreeHash,
        ),
        context_deserialize(ForkName),
        serde(bound = "E: EthSpec"),
        cfg_attr(
            feature = "arbitrary",
            derive(arbitrary::Arbitrary),
            arbitrary(bound = "E: EthSpec"),
        ),
    ),
    ref_attributes(
        derive(Debug, PartialEq, TreeHash, Serialize),
        serde(untagged, bound = "E: EthSpec"),
        tree_hash(enum_behaviour = "transparent")
    ),
    map_ref_into(AttestationRef)
)]
#[cfg_attr(
    feature = "arbitrary",
    derive(arbitrary::Arbitrary),
    arbitrary(bound = "E: EthSpec")
)]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Encode, TreeHash)]
#[serde(untagged)]
#[tree_hash(enum_behaviour = "transparent")]
#[ssz(enum_behaviour = "transparent")]
#[serde(bound = "E: EthSpec", deny_unknown_fields)]
pub struct AggregateAndProof<E: EthSpec> {
    /// The index of the validator that created the attestation.
    #[serde(with = "serde_utils::quoted_u64")]
    #[superstruct(getter(copy))]
    pub aggregator_index: u64,
    /// The aggregate attestation.
    #[superstruct(flatten)]
    pub aggregate: Attestation<E>,
    /// A proof provided by the validator that permits them to publish on the
    /// `beacon_aggregate_and_proof` gossipsub topic.
    pub selection_proof: Signature,
}

impl<'a, E: EthSpec> AggregateAndProofRef<'a, E> {
    /// Returns `true` if `validator_pubkey` signed over `self.aggregate.data.slot`.
    pub fn aggregate(self) -> AttestationRef<'a, E> {
        map_aggregate_and_proof_ref_into_attestation_ref!(&'a _, self, |inner, cons| {
            cons(&inner.aggregate)
        })
    }
}
impl<E: EthSpec> AggregateAndProof<E> {
    /// Returns `true` if `validator_pubkey` signed over `self.aggregate.data.slot`.
    pub fn aggregate<'a>(&'a self) -> AttestationRef<'a, E> {
        map_aggregate_and_proof_ref_into_attestation_ref!(&'a _, self.to_ref(), |inner, cons| {
            cons(&inner.aggregate)
        })
    }
}

impl<E: EthSpec> AggregateAndProof<E> {
    /// Produces a new `AggregateAndProof` with a `selection_proof` generated by signing
    /// `aggregate.data.slot` with `secret_key`.
    ///
    /// If `selection_proof.is_none()` it will be computed locally.
    pub fn from_aggregate(
        aggregator_index: u64,
        aggregate: AttestationRef<'_, E>,
        selection_proof: Option<SelectionProof>,
        secret_key: &SecretKey,
        fork: &Fork,
        genesis_validators_root: Hash256,
        spec: &ChainSpec,
    ) -> Self {
        let selection_proof = selection_proof.unwrap_or_else(|| {
            SelectionProof::new::<E>(
                aggregate.data().slot,
                secret_key,
                fork,
                genesis_validators_root,
                spec,
            )
        });

        Self::from_attestation(
            aggregator_index,
            aggregate.clone_as_attestation(),
            selection_proof,
        )
    }

    /// Produces a new `AggregateAndProof` given a `selection_proof`
    pub fn from_attestation(
        aggregator_index: u64,
        aggregate: Attestation<E>,
        selection_proof: SelectionProof,
    ) -> Self {
        match aggregate {
            Attestation::Base(aggregate) => Self::Base(AggregateAndProofBase {
                aggregator_index,
                aggregate,
                selection_proof: selection_proof.into(),
            }),
            Attestation::Electra(aggregate) => Self::Electra(AggregateAndProofElectra {
                aggregator_index,
                aggregate,
                selection_proof: selection_proof.into(),
            }),
        }
    }

    /// Returns `true` if `validator_pubkey` signed over `self.aggregate.data.slot`.
    pub fn is_valid_selection_proof(
        &self,
        validator_pubkey: &PublicKey,
        fork: &Fork,
        genesis_validators_root: Hash256,
        spec: &ChainSpec,
    ) -> bool {
        let target_epoch = self.aggregate().data().slot.epoch(E::slots_per_epoch());
        let domain = spec.get_domain(
            target_epoch,
            Domain::SelectionProof,
            fork,
            genesis_validators_root,
        );
        let message = self.aggregate().data().slot.signing_root(domain);
        self.selection_proof().verify(validator_pubkey, message)
    }
}

impl<E: EthSpec> SignedRoot for AggregateAndProof<E> {}
impl<E: EthSpec> SignedRoot for AggregateAndProofRef<'_, E> {}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_utils::{SeedableRng, TestRandom, XorShiftRng};
    use crate::{AttestationBase, AttestationElectra, FixedBytesExtended, MinimalEthSpec};
    use ssz::Encode;
    use tree_hash::TreeHash;

    type E = MinimalEthSpec;

    fn make_base_attestation() -> AttestationBase<E> {
        let mut rng = XorShiftRng::seed_from_u64(42);
        AttestationBase::random_for_test(&mut rng)
    }

    fn make_electra_attestation() -> AttestationElectra<E> {
        let mut rng = XorShiftRng::seed_from_u64(42);
        AttestationElectra::random_for_test(&mut rng)
    }

    #[test]
    fn from_attestation_base_variant() {
        let att = Attestation::Base(make_base_attestation());
        let proof = SelectionProof::from(Signature::empty());
        let agg = AggregateAndProof::from_attestation(7, att.clone(), proof);
        assert!(matches!(agg, AggregateAndProof::Base(_)));
        assert_eq!(agg.aggregator_index(), 7);
    }

    #[test]
    fn from_attestation_electra_variant() {
        let att = Attestation::Electra(make_electra_attestation());
        let proof = SelectionProof::from(Signature::empty());
        let agg = AggregateAndProof::from_attestation(42, att, proof);
        assert!(matches!(agg, AggregateAndProof::Electra(_)));
        assert_eq!(agg.aggregator_index(), 42);
    }

    #[test]
    fn aggregate_ref_returns_correct_variant() {
        let att_base = Attestation::Base(make_base_attestation());
        let proof = SelectionProof::from(Signature::empty());
        let agg = AggregateAndProof::from_attestation(0, att_base, proof);
        let agg_ref = agg.aggregate();
        assert!(matches!(agg_ref, AttestationRef::Base(_)));
    }

    #[test]
    fn aggregate_and_proof_ref_aggregate() {
        let att = Attestation::Electra(make_electra_attestation());
        let proof = SelectionProof::from(Signature::empty());
        let agg = AggregateAndProof::from_attestation(5, att, proof);
        let agg_ref = agg.to_ref();
        let att_ref = agg_ref.aggregate();
        assert!(matches!(att_ref, AttestationRef::Electra(_)));
    }

    #[test]
    fn ssz_encode_base_not_empty() {
        let att = Attestation::Base(make_base_attestation());
        let proof = SelectionProof::from(Signature::empty());
        let agg = AggregateAndProof::from_attestation(10, att, proof);
        let bytes = agg.as_ssz_bytes();
        assert!(!bytes.is_empty());
    }

    #[test]
    fn ssz_encode_electra_not_empty() {
        let att = Attestation::Electra(make_electra_attestation());
        let proof = SelectionProof::from(Signature::empty());
        let agg = AggregateAndProof::from_attestation(20, att, proof);
        let bytes = agg.as_ssz_bytes();
        assert!(!bytes.is_empty());
    }

    #[test]
    fn ssz_encode_deterministic() {
        let att = Attestation::Base(make_base_attestation());
        let proof = SelectionProof::from(Signature::empty());
        let agg1 = AggregateAndProof::from_attestation(10, att.clone(), proof.clone());
        let agg2 = AggregateAndProof::from_attestation(10, att, proof);
        assert_eq!(agg1.as_ssz_bytes(), agg2.as_ssz_bytes());
    }

    #[test]
    fn tree_hash_deterministic() {
        let att = Attestation::Base(make_base_attestation());
        let proof = SelectionProof::from(Signature::empty());
        let agg1 = AggregateAndProof::from_attestation(5, att.clone(), proof.clone());
        let agg2 = AggregateAndProof::from_attestation(5, att, proof);
        assert_eq!(agg1.tree_hash_root(), agg2.tree_hash_root());
    }

    #[test]
    fn tree_hash_different_index_differs() {
        let att = Attestation::Base(make_base_attestation());
        let proof = SelectionProof::from(Signature::empty());
        let agg1 = AggregateAndProof::from_attestation(1, att.clone(), proof.clone());
        let agg2 = AggregateAndProof::from_attestation(2, att, proof);
        assert_ne!(agg1.tree_hash_root(), agg2.tree_hash_root());
    }

    #[test]
    fn signed_root_impl() {
        let att = Attestation::Base(make_base_attestation());
        let proof = SelectionProof::from(Signature::empty());
        let agg = AggregateAndProof::from_attestation(0, att, proof);
        let domain = Hash256::from_low_u64_be(99);
        let root = agg.signing_root(domain);
        // signing_root should be deterministic
        assert_eq!(root, agg.signing_root(domain));
    }

    #[test]
    fn clone_and_equality() {
        let att = Attestation::Electra(make_electra_attestation());
        let proof = SelectionProof::from(Signature::empty());
        let agg = AggregateAndProof::from_attestation(33, att, proof);
        let cloned = agg.clone();
        assert_eq!(agg, cloned);
    }

    #[test]
    fn selection_proof_preserved() {
        let att = Attestation::Base(make_base_attestation());
        let empty_sig = Signature::empty();
        let proof = SelectionProof::from(empty_sig.clone());
        let agg = AggregateAndProof::from_attestation(0, att, proof);
        assert_eq!(*agg.selection_proof(), empty_sig);
    }
}
