use super::{
    ChainSpec, EthSpec, Fork, ForkName, Hash256, SecretKey, Signature, SignedRoot,
    SyncCommitteeContribution, SyncSelectionProof,
};
use crate::context_deserialize;
use crate::test_utils::TestRandom;
use serde::{Deserialize, Serialize};
use ssz_derive::{Decode, Encode};
use test_random_derive::TestRandom;
use tree_hash_derive::TreeHash;

/// A Validators aggregate sync committee contribution and selection proof.
#[cfg_attr(
    feature = "arbitrary",
    derive(arbitrary::Arbitrary),
    arbitrary(bound = "E: EthSpec")
)]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Encode, Decode, TestRandom, TreeHash)]
#[serde(bound = "E: EthSpec")]
#[context_deserialize(ForkName)]
pub struct ContributionAndProof<E: EthSpec> {
    /// The index of the validator that created the sync contribution.
    #[serde(with = "serde_utils::quoted_u64")]
    pub aggregator_index: u64,
    /// The aggregate contribution.
    pub contribution: SyncCommitteeContribution<E>,
    /// A proof provided by the validator that permits them to publish on the
    /// `sync_committee_contribution_and_proof` gossipsub topic.
    pub selection_proof: Signature,
}

impl<E: EthSpec> ContributionAndProof<E> {
    /// Produces a new `ContributionAndProof` with a `selection_proof` generated by signing
    /// `SyncAggregatorSelectionData` with `secret_key`.
    ///
    /// If `selection_proof.is_none()` it will be computed locally.
    pub fn from_aggregate(
        aggregator_index: u64,
        contribution: SyncCommitteeContribution<E>,
        selection_proof: Option<SyncSelectionProof>,
        secret_key: &SecretKey,
        fork: &Fork,
        genesis_validators_root: Hash256,
        spec: &ChainSpec,
    ) -> Self {
        let selection_proof = selection_proof
            .unwrap_or_else(|| {
                SyncSelectionProof::new::<E>(
                    contribution.slot,
                    contribution.subcommittee_index,
                    secret_key,
                    fork,
                    genesis_validators_root,
                    spec,
                )
            })
            .into();

        Self {
            aggregator_index,
            contribution,
            selection_proof,
        }
    }
}

impl<E: EthSpec> SignedRoot for ContributionAndProof<E> {}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_utils::{SeedableRng, TestRandom, XorShiftRng};
    use crate::{FixedBytesExtended, MinimalEthSpec};
    use ssz::{Decode, Encode};
    use tree_hash::TreeHash;

    type E = MinimalEthSpec;

    fn make_contribution_and_proof() -> ContributionAndProof<E> {
        let mut rng = XorShiftRng::seed_from_u64(77);
        ContributionAndProof::random_for_test(&mut rng)
    }

    #[test]
    fn fields_accessible() {
        let cap = make_contribution_and_proof();
        // Just ensure all fields are accessible and don't panic
        let _ = cap.aggregator_index;
        let _ = cap.contribution.slot;
        let _ = cap.contribution.subcommittee_index;
        let _ = &cap.selection_proof;
    }

    #[test]
    fn ssz_round_trip() {
        let cap = make_contribution_and_proof();
        let bytes = cap.as_ssz_bytes();
        let decoded = ContributionAndProof::<E>::from_ssz_bytes(&bytes).unwrap();
        assert_eq!(cap, decoded);
    }

    #[test]
    fn tree_hash_deterministic() {
        let c1 = make_contribution_and_proof();
        let c2 = make_contribution_and_proof();
        assert_eq!(c1.tree_hash_root(), c2.tree_hash_root());
    }

    #[test]
    fn clone_and_equality() {
        let cap = make_contribution_and_proof();
        let cloned = cap.clone();
        assert_eq!(cap, cloned);
    }

    #[test]
    fn signed_root_impl() {
        let cap = make_contribution_and_proof();
        let domain = Hash256::from_low_u64_be(42);
        let root = cap.signing_root(domain);
        assert_eq!(root, cap.signing_root(domain));
    }

    #[test]
    fn different_aggregator_index_different_hash() {
        let mut c1 = make_contribution_and_proof();
        let mut c2 = make_contribution_and_proof();
        c1.aggregator_index = 1;
        c2.aggregator_index = 2;
        assert_ne!(c1.tree_hash_root(), c2.tree_hash_root());
    }
}
