use super::{
    ChainSpec, ContributionAndProof, Domain, EthSpec, Fork, ForkName, Hash256, SecretKey,
    Signature, SignedRoot, SyncCommitteeContribution, SyncSelectionProof,
};
use crate::context_deserialize;
use crate::test_utils::TestRandom;
use serde::{Deserialize, Serialize};
use ssz_derive::{Decode, Encode};
use test_random_derive::TestRandom;
use tree_hash_derive::TreeHash;

/// A Validators signed contribution proof to publish on the `sync_committee_contribution_and_proof`
/// gossipsub topic.
#[cfg_attr(
    feature = "arbitrary",
    derive(arbitrary::Arbitrary),
    arbitrary(bound = "E: EthSpec")
)]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Encode, Decode, TestRandom, TreeHash)]
#[serde(bound = "E: EthSpec")]
#[context_deserialize(ForkName)]
pub struct SignedContributionAndProof<E: EthSpec> {
    /// The `ContributionAndProof` that was signed.
    pub message: ContributionAndProof<E>,
    /// The validator's signature of `message`.
    pub signature: Signature,
}

impl<E: EthSpec> SignedContributionAndProof<E> {
    /// Produces a new `SignedContributionAndProof` with a `selection_proof` generated by signing
    /// `aggregate.data.slot` with `secret_key`.
    ///
    /// If `selection_proof.is_none()` it will be computed locally.
    pub fn from_aggregate(
        aggregator_index: u64,
        contribution: SyncCommitteeContribution<E>,
        selection_proof: Option<SyncSelectionProof>,
        secret_key: &SecretKey,
        fork: &Fork,
        genesis_validators_root: Hash256,
        spec: &ChainSpec,
    ) -> Self {
        let message = ContributionAndProof::from_aggregate(
            aggregator_index,
            contribution,
            selection_proof,
            secret_key,
            fork,
            genesis_validators_root,
            spec,
        );

        let epoch = message.contribution.slot.epoch(E::slots_per_epoch());
        let domain = spec.get_domain(
            epoch,
            Domain::ContributionAndProof,
            fork,
            genesis_validators_root,
        );
        let signing_message = message.signing_root(domain);

        SignedContributionAndProof {
            message,
            signature: secret_key.sign(signing_message),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::MinimalEthSpec;
    use crate::test_utils::{SeedableRng, TestRandom, XorShiftRng};
    use ssz::{Decode, Encode};
    use tree_hash::TreeHash;

    type E = MinimalEthSpec;

    fn make_signed() -> SignedContributionAndProof<E> {
        let mut rng = XorShiftRng::seed_from_u64(55);
        SignedContributionAndProof::random_for_test(&mut rng)
    }

    #[test]
    fn fields_accessible() {
        let s = make_signed();
        let _ = s.message.aggregator_index;
        let _ = s.message.contribution.slot;
        let _ = &s.signature;
    }

    #[test]
    fn ssz_round_trip() {
        let s = make_signed();
        let bytes = s.as_ssz_bytes();
        let decoded = SignedContributionAndProof::<E>::from_ssz_bytes(&bytes).unwrap();
        assert_eq!(s, decoded);
    }

    #[test]
    fn tree_hash_deterministic() {
        let s1 = make_signed();
        let s2 = make_signed();
        assert_eq!(s1.tree_hash_root(), s2.tree_hash_root());
    }

    #[test]
    fn clone_and_equality() {
        let s = make_signed();
        let cloned = s.clone();
        assert_eq!(s, cloned);
    }

    #[test]
    fn different_aggregator_index_different_hash() {
        let mut s1 = make_signed();
        let mut s2 = make_signed();
        s1.message.aggregator_index = 100;
        s2.message.aggregator_index = 200;
        assert_ne!(s1.tree_hash_root(), s2.tree_hash_root());
    }
}
