use super::{
    AggregateAndProof, AggregateAndProofBase, AggregateAndProofElectra, AggregateAndProofRef,
};
use super::{
    Attestation, AttestationRef, ChainSpec, Domain, EthSpec, Fork, ForkName, Hash256, SecretKey,
    SelectionProof, Signature, SignedRoot,
};
use crate::context_deserialize;
use crate::test_utils::TestRandom;
use serde::{Deserialize, Serialize};
use ssz_derive::{Decode, Encode};
use superstruct::superstruct;
use test_random_derive::TestRandom;
use tree_hash_derive::TreeHash;

/// A Validators signed aggregate proof to publish on the `beacon_aggregate_and_proof`
/// gossipsub topic.
///
/// Spec v0.12.1
#[superstruct(
    variants(Base, Electra),
    variant_attributes(
        derive(
            Debug,
            Clone,
            PartialEq,
            Serialize,
            Deserialize,
            Encode,
            Decode,
            TestRandom,
            TreeHash,
        ),
        context_deserialize(ForkName),
        serde(bound = "E: EthSpec"),
        cfg_attr(
            feature = "arbitrary",
            derive(arbitrary::Arbitrary),
            arbitrary(bound = "E: EthSpec"),
        ),
    ),
    map_into(Attestation),
    map_ref_into(AggregateAndProofRef)
)]
#[cfg_attr(
    feature = "arbitrary",
    derive(arbitrary::Arbitrary),
    arbitrary(bound = "E: EthSpec")
)]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Encode, TreeHash)]
#[serde(untagged)]
#[tree_hash(enum_behaviour = "transparent")]
#[ssz(enum_behaviour = "transparent")]
#[serde(bound = "E: EthSpec", deny_unknown_fields)]
pub struct SignedAggregateAndProof<E: EthSpec> {
    /// The `AggregateAndProof` that was signed.
    #[superstruct(flatten)]
    pub message: AggregateAndProof<E>,
    /// The aggregate attestation.
    pub signature: Signature,
}

impl<E: EthSpec> SignedAggregateAndProof<E> {
    /// Produces a new `SignedAggregateAndProof` with a `selection_proof` generated by signing
    /// `aggregate.data.slot` with `secret_key`.
    ///
    /// If `selection_proof.is_none()` it will be computed locally.
    pub fn from_aggregate(
        aggregator_index: u64,
        aggregate: AttestationRef<'_, E>,
        selection_proof: Option<SelectionProof>,
        secret_key: &SecretKey,
        fork: &Fork,
        genesis_validators_root: Hash256,
        spec: &ChainSpec,
    ) -> Self {
        let message = AggregateAndProof::from_aggregate(
            aggregator_index,
            aggregate,
            selection_proof,
            secret_key,
            fork,
            genesis_validators_root,
            spec,
        );
        let target_epoch = message.aggregate().data().slot.epoch(E::slots_per_epoch());
        let domain = spec.get_domain(
            target_epoch,
            Domain::AggregateAndProof,
            fork,
            genesis_validators_root,
        );
        let signing_message = message.signing_root(domain);

        Self::from_aggregate_and_proof(message, secret_key.sign(signing_message))
    }

    /// Produces a new `SignedAggregateAndProof` given a `signature` of `aggregate`
    pub fn from_aggregate_and_proof(aggregate: AggregateAndProof<E>, signature: Signature) -> Self {
        match aggregate {
            AggregateAndProof::Base(message) => {
                SignedAggregateAndProof::Base(SignedAggregateAndProofBase { message, signature })
            }
            AggregateAndProof::Electra(message) => {
                SignedAggregateAndProof::Electra(SignedAggregateAndProofElectra {
                    message,
                    signature,
                })
            }
        }
    }

    pub fn message<'a>(&'a self) -> AggregateAndProofRef<'a, E> {
        map_signed_aggregate_and_proof_ref_into_aggregate_and_proof_ref!(
            &'a _,
            self.to_ref(),
            |inner, cons| { cons(&inner.message) }
        )
    }

    pub fn into_attestation(self) -> Attestation<E> {
        map_signed_aggregate_and_proof_into_attestation!(self, |inner, cons| {
            cons(inner.message.aggregate)
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_utils::{SeedableRng, TestRandom, XorShiftRng};
    use crate::{AttestationBase, AttestationElectra, MinimalEthSpec};
    use ssz::Encode;
    use tree_hash::TreeHash;

    type E = MinimalEthSpec;

    fn make_base_signed() -> SignedAggregateAndProof<E> {
        let mut rng = XorShiftRng::seed_from_u64(99);
        let att = Attestation::Base(AttestationBase::random_for_test(&mut rng));
        let proof = SelectionProof::from(Signature::empty());
        let agg = AggregateAndProof::from_attestation(7, att, proof);
        SignedAggregateAndProof::from_aggregate_and_proof(agg, Signature::empty())
    }

    fn make_electra_signed() -> SignedAggregateAndProof<E> {
        let mut rng = XorShiftRng::seed_from_u64(99);
        let att = Attestation::Electra(AttestationElectra::random_for_test(&mut rng));
        let proof = SelectionProof::from(Signature::empty());
        let agg = AggregateAndProof::from_attestation(8, att, proof);
        SignedAggregateAndProof::from_aggregate_and_proof(agg, Signature::empty())
    }

    #[test]
    fn from_aggregate_and_proof_base() {
        let signed = make_base_signed();
        assert!(matches!(signed, SignedAggregateAndProof::Base(_)));
    }

    #[test]
    fn from_aggregate_and_proof_electra() {
        let signed = make_electra_signed();
        assert!(matches!(signed, SignedAggregateAndProof::Electra(_)));
    }

    #[test]
    fn message_returns_correct_ref() {
        let signed = make_base_signed();
        let msg_ref = signed.message();
        assert!(matches!(msg_ref, AggregateAndProofRef::Base(_)));
        assert_eq!(msg_ref.aggregator_index(), 7);
    }

    #[test]
    fn into_attestation_base() {
        let signed = make_base_signed();
        let att = signed.into_attestation();
        assert!(matches!(att, Attestation::Base(_)));
    }

    #[test]
    fn into_attestation_electra() {
        let signed = make_electra_signed();
        let att = signed.into_attestation();
        assert!(matches!(att, Attestation::Electra(_)));
    }

    #[test]
    fn ssz_encode_base_not_empty() {
        let signed = make_base_signed();
        let bytes = signed.as_ssz_bytes();
        assert!(!bytes.is_empty());
    }

    #[test]
    fn ssz_encode_electra_not_empty() {
        let signed = make_electra_signed();
        let bytes = signed.as_ssz_bytes();
        assert!(!bytes.is_empty());
    }

    #[test]
    fn ssz_encode_deterministic() {
        let s1 = make_base_signed();
        let s2 = make_base_signed();
        assert_eq!(s1.as_ssz_bytes(), s2.as_ssz_bytes());
    }

    #[test]
    fn tree_hash_deterministic() {
        let s1 = make_base_signed();
        let s2 = make_base_signed();
        assert_eq!(s1.tree_hash_root(), s2.tree_hash_root());
    }

    #[test]
    fn clone_and_equality() {
        let signed = make_electra_signed();
        let cloned = signed.clone();
        assert_eq!(signed, cloned);
    }

    #[test]
    fn signature_preserved() {
        let signed = make_base_signed();
        assert_eq!(*signed.signature(), Signature::empty());
    }
}
